-- Cria tabela Produto
CREATE TABLE PRODUTO (
    id_produto INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    categ_prod VARCHAR (20),
    desc_prod VARCHAR(50),
    unidade VARCHAR(20),
    valor_prod DOUBLE NOT NULL,
    enabled BOOLEAN
);
/*
-- Criando tabela de filial
CREATE TABLE FILIAL (
    ID_FILIAL INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    CNPJ INTEGER(14),
    NOME VARCHAR(60),
    NOME_FANTASIA VARCHAR(35),
    CIDADE VARCHAR (20),
    ESTADO VARCHAR (20),
    TELEFONE INTEGER (10),
);

-- Cria tabela ESOQUE
CREATE TABLE ESTOQUE (
    ID_ESTOQUE INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    DESC_ESTOQUE VARCHAR (20),
    FK_FILIAL INTEGER NOT NULL REFERENCES FILIAL(ID_FILIAL),
    ENABLED BOOLEAN
);

-- CRIA TABELA MOVIMENTACAO DE ESTOQUE (BASICAMENTE NOSSA TABELA Venda_Produto DO PI PASSADO)
CREATE TABLE MOVIMENTAÇÃO (
    ID_MOVIMENTO INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    FK_PRODUTO INTEGER NOT NULL REFERENCES PRODUTO(ID_PRODUTO),
    FK_FILIAL INTEGER NOT NULL REFERENCES FILIAL(ID_FILIAL),
    FK_ESTOQUE INTEGER NOT NULL REFERENCES ESTOQUE(ID_ESTOQUE),
    ENABLED BOOLEAN
);


/*
CREATE TABLE Venda_Produto (
    produto_id INTEGER NOT NULL REFERENCES produto(id_produto),
    id_venda INTEGER NOT NULL REFERENCES venda (id_venda)    
);
*/